# Generated by Django 4.2.2 on 2023-06-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(max_length=40)),
                ("route", models.FileField(blank=True, null=True, upload_to="media/")),
                ("content", models.TextField()),
            ],
            options={
                "db_table": "txt_test",
            },
        ),
    ]
