# Generated by Django 4.2.2 on 2023-06-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("audio_example", models.FileField(default="", upload_to="")),
                ("audio_myvoice", models.FileField(default="", upload_to="")),
                ("keyword", models.CharField(default="", max_length=1000)),
                ("title", models.CharField(default="", max_length=500)),
                ("ko_title", models.CharField(default="", max_length=500)),
                ("content", models.TextField()),
                ("ko_content", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
            options={
                "db_table": "ai_result",
            },
        ),
    ]
